# Generated by Django 2.1.7 on 2019-02-14 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trel', '0002_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='action',
            field=models.CharField(max_length=32, null=True, verbose_name='Action'),
        ),
        migrations.AddField(
            model_name='log',
            name='actor',
            field=models.CharField(max_length=32, null=True, verbose_name='Actor'),
        ),
        migrations.AddField(
            model_name='log',
            name='complaint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trel.Complaint', verbose_name='Complaint'),
        ),
    ]
