# Generated by Django 2.1.7 on 2019-02-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trel', '0003_auto_20190214_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='username',
            field=models.CharField(max_length=30, null=True, verbose_name='Instagram Username'),
        ),
    ]
