# Generated by Django 2.1.7 on 2019-02-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trel', '0004_complaint_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='comment_id',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='post_id',
        ),
        migrations.AddField(
            model_name='complaint',
            name='instagram_comment_id',
            field=models.CharField(max_length=20, null=True, verbose_name='Instagram Comment ID'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='instagram_post_id',
            field=models.CharField(max_length=35, null=True, verbose_name='Instagram Post ID'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='trello_id',
            field=models.CharField(db_index=True, max_length=32, null=True, verbose_name='Trello Card ID'),
        ),
    ]
