# Generated by Django 2.1.7 on 2019-02-24 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trel', '0006_auto_20190215_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='ready_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='resolved_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='wip_at',
            field=models.DateTimeField(null=True),
        ),
    ]
