# Generated by Django 2.1.7 on 2019-02-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trel', '0007_auto_20190224_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(db_index=True, max_length=10, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='instagram_comment_id',
            field=models.CharField(db_index=True, max_length=20, null=True, verbose_name='Instagram Comment ID'),
        ),
    ]
