# Generated by Django 2.1.7 on 2019-02-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Complaint ID')),
                ('text', models.TextField(verbose_name='Complaint Text')),
                ('state', models.IntegerField(verbose_name='State')),
                ('category', models.CharField(max_length=10, verbose_name='Category')),
                ('post_id', models.CharField(max_length=35, verbose_name='Instagram Post ID')),
                ('comment_id', models.CharField(max_length=20, verbose_name='Instagram Post ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ready_at', models.DateTimeField()),
                ('wip_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
            },
        ),
    ]
